import { Edit3, Trash2 } from 'lucide-react'
import { Link } from 'react-router-dom'
import type { Grupo } from '../../types/grupo'
import { GrupoStatusBadge } from './GrupoStatusBadge'

interface Props { grupos: Grupo[]; onDelete: (grupo: Grupo) => void; onToggle: (grupo: Grupo) => void; busyId?: string }
export function GrupoTable({ grupos, onDelete, onToggle, busyId }: Props) {
  return <div className="overflow-hidden rounded-2xl bg-white shadow-sm"><div className="hidden overflow-x-auto md:block"><table className="w-full text-left text-sm"><thead className="border-b border-ink/10 bg-paper text-xs uppercase tracking-wider text-ink/45"><tr>{['Grupo', 'Descrição', 'Produtos', 'Ordem', 'Status', 'Ações'].map((label) => <th key={label} className="px-5 py-4 font-semibold">{label}</th>)}</tr></thead><tbody className="divide-y divide-ink/10">{grupos.map((grupo) => <tr key={grupo.id} className="hover:bg-paper/70"><td className="px-5 py-4 font-semibold">{grupo.nome}</td><td className="max-w-xs px-5 py-4 text-ink/55"><span className="line-clamp-2">{grupo.descricao || '-'}</span></td><td className="px-5 py-4 text-ink/45">{grupo.quantidadeProdutos === undefined ? 'Indisponível' : `${grupo.quantidadeProdutos} produto(s)`}</td><td className="px-5 py-4 font-semibold">{grupo.ordem}</td><td className="px-5 py-4"><GrupoStatusBadge ativo={grupo.ativo} /></td><td className="px-5 py-4"><div className="flex items-center gap-1"><Link aria-label={`Editar ${grupo.nome}`} to={`/admin/grupos/${grupo.id}`} className="rounded-lg p-2 text-ink/50 hover:bg-mint hover:text-teal"><Edit3 size={17} /></Link><button disabled={busyId === grupo.id} onClick={() => onToggle(grupo)} className="rounded-lg px-2 text-xs font-semibold text-teal hover:bg-mint">{grupo.ativo ? 'Desativar' : 'Ativar'}</button><button aria-label={`Excluir ${grupo.nome}`} onClick={() => onDelete(grupo)} className="rounded-lg p-2 text-ink/50 hover:bg-rose-50 hover:text-rose-600"><Trash2 size={17} /></button></div></td></tr>)}</tbody></table></div><div className="divide-y divide-ink/10 md:hidden">{grupos.map((grupo) => <article key={grupo.id} className="p-5"><div className="flex justify-between gap-3"><div className="min-w-0"><h2 className="truncate font-semibold">{grupo.nome}</h2><p className="mt-1 line-clamp-2 text-sm text-ink/50">{grupo.descricao || 'Sem descrição'}</p></div><GrupoStatusBadge ativo={grupo.ativo} /></div><div className="mt-4 flex items-center justify-between"><span className="text-xs text-ink/50">Ordem: <strong className="text-ink">{grupo.ordem}</strong> · Produtos: {grupo.quantidadeProdutos === undefined ? 'indisponível' : grupo.quantidadeProdutos}</span><div className="flex items-center gap-1"><Link aria-label={`Editar ${grupo.nome}`} to={`/admin/grupos/${grupo.id}`} className="rounded-lg bg-mint p-2 text-teal"><Edit3 size={16} /></Link><button disabled={busyId === grupo.id} onClick={() => onToggle(grupo)} className="rounded-lg px-2 text-xs font-semibold text-teal">{grupo.ativo ? 'Desativar' : 'Ativar'}</button><button aria-label={`Excluir ${grupo.nome}`} onClick={() => onDelete(grupo)} className="rounded-lg bg-rose-50 p-2 text-rose-600"><Trash2 size={16} /></button></div></div></article>)}</div>{grupos.length === 0 && <p className="p-12 text-center text-sm text-ink/50">Nenhum grupo encontrado.</p>}</div>
}
