import { History } from 'lucide-react'
import type { Categoria } from '../../types/categoria'
import type { Grupo } from '../../types/grupo'
import type { EstoqueProduto } from '../../types/estoque'
import { EstoqueStatusBadge } from './EstoqueStatusBadge'

interface Props { produtos: EstoqueProduto[]; categorias: Categoria[]; grupos: Grupo[]; onHistory: (produto: EstoqueProduto) => void }
export function EstoqueTable({ produtos, categorias, grupos, onHistory }: Props) {
  const category = (id: string) => categorias.find((item) => item.id === id)?.nome ?? 'Sem categoria'
  const group = (id: string) => grupos.find((item) => item.id === id)?.nome ?? 'Sem grupo'
  return <div className="overflow-hidden rounded-2xl bg-white shadow-sm"><div className="hidden overflow-x-auto md:block"><table className="w-full text-left text-sm"><thead className="border-b border-ink/10 bg-paper text-xs uppercase tracking-wider text-ink/45"><tr>{['Produto', 'Categoria', 'Grupo', 'Atual', 'Mínimo', 'Situação', 'Ações'].map((label) => <th key={label} className="px-5 py-4 font-semibold">{label}</th>)}</tr></thead><tbody className="divide-y divide-ink/10">{produtos.map((produto) => <tr key={produto.id} className={produto.estoqueAtual <= 0 ? 'bg-rose-50/40' : 'hover:bg-paper/70'}><td className="px-5 py-4"><p className="font-semibold">{produto.nome}</p><p className="mt-1 text-xs text-ink/45">{produto.codigo || 'Sem código'}</p></td><td className="px-5 py-4 text-ink/55">{category(produto.categoriaId)}</td><td className="px-5 py-4 text-ink/55">{group(produto.grupoId)}</td><td className="px-5 py-4 font-display text-lg font-bold">{produto.estoqueAtual}</td><td className="px-5 py-4 text-ink/55">{produto.estoqueMinimo}</td><td className="px-5 py-4"><EstoqueStatusBadge atual={produto.estoqueAtual} minimo={produto.estoqueMinimo} /></td><td className="px-5 py-4"><button onClick={() => onHistory(produto)} className="flex items-center gap-2 rounded-lg px-2 py-2 text-xs font-semibold text-teal hover:bg-mint"><History size={16} />Histórico</button></td></tr>)}</tbody></table></div><div className="divide-y divide-ink/10 md:hidden">{produtos.map((produto) => <article key={produto.id} className={`p-5 ${produto.estoqueAtual <= 0 ? 'bg-rose-50/40' : ''}`}><div className="flex justify-between gap-3"><div><h2 className="font-semibold">{produto.nome}</h2><p className="mt-1 text-xs text-ink/50">{produto.codigo || 'Sem código'}</p></div><EstoqueStatusBadge atual={produto.estoqueAtual} minimo={produto.estoqueMinimo} /></div><div className="mt-4 grid grid-cols-2 gap-3 text-sm"><span><small className="block text-xs text-ink/45">Categoria</small>{category(produto.categoriaId)}</span><span><small className="block text-xs text-ink/45">Grupo</small>{group(produto.grupoId)}</span><span><small className="block text-xs text-ink/45">Atual</small><strong className="font-display text-lg">{produto.estoqueAtual}</strong></span><span><small className="block text-xs text-ink/45">Mínimo</small>{produto.estoqueMinimo}</span></div><button onClick={() => onHistory(produto)} className="mt-4 flex items-center gap-2 text-xs font-semibold text-teal"><History size={15} />Ver histórico</button></article>)}</div>{produtos.length === 0 && <p className="p-12 text-center text-sm text-ink/50">Nenhum produto encontrado.</p>}</div>
}
