import { X } from 'lucide-react'
import { useQuery } from '@tanstack/react-query'
import { listarHistorico } from '../../api/estoque'
import type { EstoqueProduto, HistoricoMovimentacao } from '../../types/estoque'

function date(value?: string) { return value ? new Intl.DateTimeFormat('pt-BR', { dateStyle: 'short', timeStyle: 'short' }).format(new Date(value)) : '-' }
export function EstoqueHistorico({ produto, onClose }: { produto: EstoqueProduto; onClose: () => void }) {
  const query = useQuery({ queryKey: ['historico-estoque', produto.id], queryFn: () => listarHistorico(produto.id) })
  return <div className="fixed inset-0 z-50 flex justify-end bg-ink/30"><aside className="h-full w-full max-w-lg overflow-y-auto bg-white p-6 shadow-2xl sm:p-8"><div className="flex items-start justify-between"><div><p className="text-xs font-semibold uppercase tracking-widest text-teal">Movimentações</p><h2 className="mt-2 font-display text-2xl font-bold">{produto.nome}</h2></div><button aria-label="Fechar histórico" onClick={onClose} className="rounded-full p-2 text-ink/50 hover:bg-paper"><X size={20} /></button></div>{query.isLoading && <p className="mt-8 text-sm text-ink/50">Carregando histórico...</p>}{query.isError && <p className="mt-8 rounded-xl bg-rose-50 p-4 text-sm text-rose-700">Não foi possível carregar o histórico.</p>}<div className="mt-8 space-y-4">{query.data?.map((item: HistoricoMovimentacao, index) => <article key={item.id ?? `${item.data}-${index}`} className="border-l-2 border-teal/30 pl-4"><div className="flex items-center justify-between gap-3"><strong className="text-sm">{item.tipo ?? 'Movimentação'}</strong><span className="text-xs text-ink/45">{date(item.data ?? item.dataCriacao)}</span></div><p className={`mt-2 font-display text-lg font-bold ${(item.quantidade ?? 0) < 0 ? 'text-coral' : 'text-teal'}`}>{item.quantidade !== undefined ? `${item.quantidade > 0 ? '+' : ''}${item.quantidade}` : '-'}</p><p className="mt-1 text-xs text-ink/55">Anterior: {item.estoqueAnterior ?? '-'} · Posterior: {item.estoquePosterior ?? '-'}</p><p className="mt-2 text-sm text-ink/60">{item.observacao || 'Sem observação'}</p>{item.usuario && <p className="mt-1 text-xs text-ink/40">Usuário: {item.usuario}</p>}</article>)}{query.data?.length === 0 && <p className="text-sm text-ink/50">Nenhuma movimentação registrada.</p>}</div></aside></div>
}
