import { useEffect } from 'react'
import { X } from 'lucide-react'
import { useForm } from 'react-hook-form'
import { zodResolver } from '@hookform/resolvers/zod'
import { z } from 'zod'
import type { EstoqueProduto } from '../../types/estoque'

const schema = z.object({ produtoId: z.string().min(1, 'Selecione um produto'), tipo: z.enum(['entrada', 'ajuste']), valor: z.coerce.number({ invalid_type_error: 'Informe um valor' }).min(0, 'O valor não pode ser negativo'), observacao: z.string().optional() })
export type MovimentacaoFormData = z.infer<typeof schema>
interface Props { produtos: EstoqueProduto[]; selectedId?: string; isSaving: boolean; onSubmit: (data: MovimentacaoFormData) => Promise<void>; onClose: () => void }
export function MovimentacaoModal({ produtos, selectedId, isSaving, onSubmit, onClose }: Props) {
  const { register, watch, handleSubmit, reset, formState: { errors } } = useForm<MovimentacaoFormData>({ resolver: zodResolver(schema), defaultValues: { produtoId: selectedId ?? '', tipo: 'entrada', valor: 0, observacao: '' } })
  useEffect(() => { reset({ produtoId: selectedId ?? '', tipo: 'entrada', valor: 0, observacao: '' }) }, [selectedId, reset])
  const product = produtos.find((item) => item.id === watch('produtoId')); const type = watch('tipo'); const value = watch('valor') || 0; const difference = type === 'ajuste' ? value - (product?.estoqueAtual ?? 0) : value; const after = (product?.estoqueAtual ?? 0) + difference; const input = 'mt-2 w-full rounded-xl border border-ink/15 bg-paper px-4 py-3 outline-none focus:border-teal focus:ring-4 focus:ring-teal/10'
  return <div className="fixed inset-0 z-50 grid place-items-center bg-ink/40 p-4"><div className="max-h-[90vh] w-full max-w-lg overflow-y-auto rounded-2xl bg-white p-6 shadow-2xl sm:p-8"><div className="flex items-start justify-between"><div><p className="text-xs font-semibold uppercase tracking-widest text-teal">Estoque</p><h2 className="mt-2 font-display text-2xl font-bold">Movimentar estoque</h2></div><button aria-label="Fechar modal" onClick={onClose} className="rounded-full p-2 text-ink/50 hover:bg-paper"><X size={20} /></button></div><form onSubmit={handleSubmit(onSubmit)} className="mt-7 space-y-5"><label className="block text-sm font-semibold">Produto<select {...register('produtoId')} className={input}><option value="">Selecione um produto</option>{produtos.filter((item) => item.ativo).map((item) => <option key={item.id} value={item.id}>{item.nome} · {item.codigo || 'sem código'} · atual: {item.estoqueAtual}</option>)}</select>{errors.produtoId && <span className="mt-1 block text-xs text-rose-600">{errors.produtoId.message}</span>}</label><label className="block text-sm font-semibold">Tipo<select {...register('tipo')} className={input}><option value="entrada">Entrada</option><option value="ajuste">Ajuste</option></select></label><label className="block text-sm font-semibold">{type === 'entrada' ? 'Quantidade de entrada' : 'Novo estoque'}<input {...register('valor')} type="number" min="0" step="0.01" className={input} />{errors.valor && <span className="mt-1 block text-xs text-rose-600">{errors.valor.message}</span>}</label>{product && <div className="rounded-xl bg-mint p-4 text-sm"><p>Estoque atual: <strong>{product.estoqueAtual}</strong></p>{type === 'entrada' ? <p className="mt-1">Novo estoque: <strong>{after}</strong></p> : <p className="mt-1">Diferença: <strong className={difference < 0 ? 'text-coral' : 'text-teal'}>{difference > 0 ? '+' : ''}{difference}</strong> unidades</p>}<p className="mt-1 text-xs text-ink/50">{type === 'ajuste' ? `Ajuste de ${difference > 0 ? '+' : ''}${difference} unidades.` : `Entrada de +${value} unidades.`}</p></div>}<label className="block text-sm font-semibold">Observação<textarea {...register('observacao')} rows={3} className={input} placeholder="Ex.: Contagem física" /></label><button disabled={isSaving} className="w-full rounded-xl bg-teal py-3.5 font-semibold text-white hover:bg-teal/90 disabled:cursor-wait disabled:opacity-60">{isSaving ? 'Confirmando...' : 'Confirmar movimentação'}</button></form></div></div>
}
