import { useEffect, useState } from 'react'
import { Image, Save } from 'lucide-react'
import { useForm } from 'react-hook-form'
import { zodResolver } from '@hookform/resolvers/zod'
import { z } from 'zod'
import type { Categoria } from '../../types/categoria'

const schema = z.object({ nome: z.string().trim().min(1, 'Informe o nome da categoria'), descricao: z.string().optional(), imagemUrl: z.union([z.literal(''), z.string().url('Informe uma URL válida')]).optional(), ordem: z.coerce.number().int('A ordem deve ser um número inteiro').min(0, 'A ordem não pode ser negativa'), ativo: z.boolean() })
export type CategoriaFormData = z.infer<typeof schema>
interface Props { categoria?: Categoria; onSubmit: (data: CategoriaFormData) => Promise<void>; isSaving: boolean }
function FieldError({ message }: { message?: string }) { return message ? <span className="mt-1 block text-xs text-rose-600">{message}</span> : null }
export function CategoriaForm({ categoria, onSubmit, isSaving }: Props) {
  const { register, watch, reset, handleSubmit, formState: { errors } } = useForm<CategoriaFormData>({ resolver: zodResolver(schema), defaultValues: { nome: categoria?.nome ?? '', descricao: categoria?.descricao ?? '', imagemUrl: categoria?.imagemUrl ?? '', ordem: categoria?.ordem ?? 0, ativo: categoria?.ativo ?? true } })
  const imageUrl = watch('imagemUrl'); const [imageError, setImageError] = useState(false)
  useEffect(() => { if (categoria) reset({ nome: categoria.nome, descricao: categoria.descricao ?? '', imagemUrl: categoria.imagemUrl ?? '', ordem: categoria.ordem, ativo: categoria.ativo }) }, [categoria, reset])
  const input = 'mt-2 w-full rounded-xl border border-ink/15 bg-paper px-4 py-3 outline-none transition focus:border-teal focus:ring-4 focus:ring-teal/10'
  return <form onSubmit={handleSubmit(onSubmit)} className="rounded-2xl bg-white p-5 shadow-sm sm:p-6"><div className="grid gap-5 sm:grid-cols-2"><label className="text-sm font-semibold">Nome *<input {...register('nome')} className={input} placeholder="Ex.: Bebidas" /><FieldError message={errors.nome?.message} /></label><label className="text-sm font-semibold">Ordem<input {...register('ordem')} type="number" min="0" step="1" className={input} /><FieldError message={errors.ordem?.message} /></label><label className="text-sm font-semibold sm:col-span-2">Descrição<textarea {...register('descricao')} rows={4} className={input} placeholder="Descreva esta categoria." /></label><label className="text-sm font-semibold sm:col-span-2">URL da imagem<input {...register('imagemUrl', { onChange: () => setImageError(false) })} type="url" className={input} placeholder="https://exemplo.com/imagem.jpg" /><p className="mt-1 text-xs font-normal text-ink/45">A API atual suporta imagem por URL. Upload de arquivo será habilitado quando houver endpoint específico.</p><FieldError message={errors.imagemUrl?.message} /></label><div className="sm:col-span-2">{imageUrl && !errors.imagemUrl && !imageError ? <div className="relative h-40 overflow-hidden rounded-xl bg-mint"><img src={imageUrl} alt="Preview da categoria" className="h-full w-full object-cover" onError={() => setImageError(true)} /></div> : <div className="grid h-32 place-items-center rounded-xl bg-paper text-ink/35"><Image size={26} /></div>}{imageError && <p className="mt-1 text-xs text-rose-600">Não foi possível carregar a imagem informada.</p>}</div><label className="flex cursor-pointer items-center gap-2 text-sm font-semibold"><input {...register('ativo')} type="checkbox" className="h-4 w-4 accent-teal" />Categoria ativa</label></div><div className="mt-6 flex justify-end border-t border-ink/10 pt-5"><button disabled={isSaving} className="flex items-center gap-2 rounded-xl bg-teal px-5 py-3 font-semibold text-white hover:bg-teal/90 disabled:cursor-wait disabled:opacity-60"><Save size={18} />{isSaving ? 'Salvando...' : 'Salvar categoria'}</button></div></form>
}
