import { useEffect } from 'react'
import { Save } from 'lucide-react'
import { useForm } from 'react-hook-form'
import { zodResolver } from '@hookform/resolvers/zod'
import { z } from 'zod'
import type { Categoria, Produto } from '../../types/produto'
import type { Grupo } from '../../types/grupo'
import { GrupoSelect } from '../grupo/GrupoSelect'

const schema = z.object({ nome: z.string().trim().min(1, 'Informe o nome do produto'), codigo: z.string().optional(), categoriaId: z.string().min(1, 'Selecione uma categoria'), grupoId: z.string().min(1, 'Selecione um grupo'), descricao: z.string().optional(), preco: z.coerce.number({ invalid_type_error: 'Informe o preço' }).min(0, 'O preço não pode ser negativo'), estoqueMinimo: z.coerce.number({ invalid_type_error: 'Informe o estoque mínimo' }).min(0, 'O estoque mínimo não pode ser negativo'), ativo: z.boolean(), destaque: z.boolean() })
export type ProdutoFormData = z.infer<typeof schema>
interface Props { produto?: Produto; categorias: Categoria[]; grupos: Grupo[]; onSubmit: (data: ProdutoFormData) => Promise<void>; isSaving: boolean }
function FieldError({ message }: { message?: string }) { return message ? <span className="mt-1 block text-xs text-rose-600">{message}</span> : null }
export function ProdutoForm({ produto, categorias, grupos, onSubmit, isSaving }: Props) {
  const { register, handleSubmit, reset, formState: { errors } } = useForm<ProdutoFormData>({ resolver: zodResolver(schema), defaultValues: { nome: produto?.nome ?? '', codigo: produto?.codigo ?? '', categoriaId: produto?.categoriaId ?? '', grupoId: produto?.grupoId ?? '', descricao: produto?.descricao ?? '', preco: produto?.preco ?? 0, estoqueMinimo: produto?.estoqueMinimo ?? 0, ativo: produto?.ativo ?? true, destaque: produto?.destaque ?? false } })
  useEffect(() => { if (produto) reset({ nome: produto.nome, codigo: produto.codigo ?? '', categoriaId: produto.categoriaId, grupoId: produto.grupoId, descricao: produto.descricao ?? '', preco: produto.preco, estoqueMinimo: produto.estoqueMinimo, ativo: produto.ativo, destaque: produto.destaque }) }, [produto, reset])
  const input = 'mt-2 w-full rounded-xl border border-ink/15 bg-paper px-4 py-3 outline-none transition focus:border-teal focus:ring-4 focus:ring-teal/10'
  return <form onSubmit={handleSubmit(onSubmit)} className="rounded-2xl bg-white p-5 shadow-sm sm:p-6"><div className="grid gap-5 sm:grid-cols-2"><label className="text-sm font-semibold">Nome *<input {...register('nome')} className={input} placeholder="Ex.: Café especial" /><FieldError message={errors.nome?.message} /></label><label className="text-sm font-semibold">Código<input {...register('codigo')} className={input} placeholder="SKU-001" /><FieldError message={errors.codigo?.message} /></label><label className="text-sm font-semibold">Categoria *<select {...register('categoriaId')} className={input}><option value="">Selecione uma categoria</option>{categorias.filter((categoria) => categoria.ativo).map((categoria) => <option key={categoria.id} value={categoria.id}>{categoria.nome}</option>)}</select><FieldError message={errors.categoriaId?.message} /></label><label className="text-sm font-semibold">Grupo *<GrupoSelect grupos={grupos} registration={register('grupoId')} className={input} /><FieldError message={errors.grupoId?.message} /></label><label className="text-sm font-semibold">Preço *<input {...register('preco')} type="number" min="0" step="0.01" className={input} placeholder="0,00" /><FieldError message={errors.preco?.message} /></label><label className="text-sm font-semibold">Estoque mínimo *<input {...register('estoqueMinimo')} type="number" min="0" step="0.01" className={input} /><FieldError message={errors.estoqueMinimo?.message} /></label><div className="flex items-end gap-6 pb-1"><label className="flex cursor-pointer items-center gap-2 text-sm font-semibold"><input {...register('ativo')} type="checkbox" className="h-4 w-4 accent-teal" />Ativo</label><label className="flex cursor-pointer items-center gap-2 text-sm font-semibold"><input {...register('destaque')} type="checkbox" className="h-4 w-4 accent-coral" />Destaque</label></div><label className="text-sm font-semibold sm:col-span-2">Descrição<textarea {...register('descricao')} rows={5} className={input} placeholder="Descreva o produto para sua equipe e catálogo." /></label></div><div className="mt-6 flex justify-end border-t border-ink/10 pt-5"><button disabled={isSaving} className="flex items-center gap-2 rounded-xl bg-teal px-5 py-3 font-semibold text-white transition hover:bg-teal/90 disabled:cursor-wait disabled:opacity-60"><Save size={18} />{isSaving ? 'Salvando...' : 'Salvar produto'}</button></div></form>
}
